### ISSUE TITLE
能和moon同时存在吗？

### ISSUE THREAD

**Issue by Y-pandaman** [Jonnyan404/zerotier-planet#7]
你好，我在阿里云服务器已经建了moon节点（使用官方的网络）， 如果再在服务器部署这个planet节点，会和moon节点冲突吗？

**Comment by Jonnyan404** [comment]
可以,不冲突

**Comment by Y-pandaman** [comment]
我在运行 docker-compose up -d的时候，报以下错误，请问是什么情况？
Starting ztncui ... 

ERROR: for ztncui  a bytes-like object is required, not 'str'

ERROR: for ztncui  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.22/containers/fbcd59ec145d0712858f3a9ed9b188ff0dfee5478e74567e8484200f5fca2570/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/compose/service.py", line 625, in start_container
    container.start()
  File "/usr/lib/python3/dist-packages/compose/container.py", line 241, in start
    return self.client.start(self.id, **options)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/container.py", line 1095, in start
    self._raise_for_status(res)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'driver failed programming external connectivity on endpoint ztncui (1781d1e971f6bc38d292a75c61fe73db6a788d0e9c64450fc08523a3960175e0): Error starting userland proxy: listen tcp4 0.0.0.0:4000: bind: address already in use'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1107, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1088, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 565, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 548, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 567, in execute_convergence_plan
    return self._execute_convergence_start(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 506, in _execute_convergence_start
    _, errors = parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 508, in <lambda>
    lambda c: self.start_container_if_stopped(c, attach_logs=not detached, quiet=True),
  File "/usr/lib/python3/dist-packages/compose/service.py", line 620, in start_container_if_stopped
    return self.start_container(container)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 627, in start_container
    if "driver failed programming external connectivity" in ex.explanation:
TypeError: a bytes-like object is required, not 'str'

**Comment by Y-pandaman** [comment]
使用 apt-get install docker-compose安装的，docker-compose version 1.25.0

**Comment by Jonnyan404** [comment]
直接执行:`docker run --restart=on-failure:3 -d --name ztncui -e HTTP_PORT=4000 -e HTTP_ALL_INTERFACES=yes -e ZTNCUI_PASSWD=mrdoc.fun -p 4000:4000 keynetworks/ztncui`等效于上面的docker-compose.

**Comment by Y-pandaman** [comment]
能用了，但是4000端口被占用，改成了 ```docker run --restart=on-failure:3 -d --name ztncui -e HTTP_PORT=4001 -e HTTP_ALL_INTERFACES=yes -e ZTNCUI_PASSWD=mrdoc.fun -p 4001:4001 keynetworks/ztncui```,还有docker-compose.yml里也改成了4001

**Comment by Y-pandaman** [comment]
安卓加入网络后，后台显示在线，windows显示离线，但是它俩能ping通

**Comment by Jonnyan404** [comment]
> 安卓加入网络后，后台显示在线，windows显示离线，但是它俩能ping通

之前有人反馈过了,可能是缓存或者内部没刷新过来吧,具体原因,我也不清楚,可以去  ztncui 项目作者那里的issue去翻翻看.

**Comment by Y-pandaman** [comment]
感觉对5G不友好，手机连5Gwifi后，一直ping不通，但是用手机4G流量，马上就ping通了，70ms左右，而且两台电脑之间相互ping，连了5G网络，延迟很大。400ms，
